// <auto-generated />
using ApartmentManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ApartmentManagementSystem.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260606120000_AddRazorpayOrderIdToMaintenance")]
    partial class AddRazorpayOrderIdToMaintenance
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
